#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
ls $OPENSHIFT_REPO_DIR
python $OPENSHIFT_REPO_DIR/wsgi/mybottleapp.py init-db
